apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker
  name: broker
spec:
  type: LoadBalancer
  ports:
    - name: "port-0"
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: "port-1"
      protocol: TCP
      port: 9101
      targetPort: 9101
    - name: "port-2"
      protocol: TCP
      port: 29092
      targetPort: 29092
  selector:
    app: broker
status:
  loadBalancer: {}
