apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kafka-connect-cluster
  name: kafka-connect-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
