apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-connect-cluster
  name: kafka-connect-cluster
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    app: kafka-connect-cluster
status:
  loadBalancer: {}
