apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: avro-schema-registry
  name: avro-schema-registry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
