apiVersion: v1
kind: Service
metadata:
  labels:
    app: avro-schema-registry
  name: avro-schema-registry-service
spec:
  type: LoadBalancer
  ports:
    - name: "port-0"
      protocol: TCP
      port: 8089
      targetPort: 8089
  selector:
    app: avro-schema-registry
status:
  loadBalancer: {}
